# Generated by Django 5.0a1 on 2023-10-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favs',
        ),
    ]
