# Generated by Django 5.0a1 on 2023-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
        ('users', '0002_remove_user_favs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(related_name='favs', to='rooms.room'),
        ),
    ]
