# Generated by Django 5.0a1 on 2023-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='lat',
            field=models.DecimalField(decimal_places=13, max_digits=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='lng',
            field=models.DecimalField(decimal_places=13, max_digits=15),
        ),
    ]
